name: GrubsPlugin 
main: com.selfequalsthis.grubsplugin.GrubsPlugin
version: 0.1 

commands:
    buildmode:
        description: Build Mode 
        usage: /<command> [on|off]
    timelock:
        description: Lock time to a specific timestamp.
        usage: /<command> [off|on|day|night|<int 0:24000>
    storm:
        description: Enable/Disable rain storms.
        usage: /<command> [on|off]
    thunder:
        description: Enable/Disable lightening and thunder.
        usage: /<command> [on|off]
    strike:
        description: Hit a player with lightening, but do no damage.
        usage: /<command> <player>
    zap:
        description: Hit a player with lightening, doing damage.
        usage: /<command> <player>
    goto:
        description: Teleport to a location or player. 
        usage: /<command> [<player>|<preset location>|last|grave|quit]
    fetch:
        description: Teleport a player to user. 
        usage: /<command> <player>
    send:
        description: Teleport a player to a user or preset. 
        usage: /<command> <player> [<player>|<preset name>]
    tpset:
        description: Store the current location as a preset. 
        usage: /<command> <preset name> 
    tpdel:
        description: Remove a previously stored preset.
        usage: /<command> <preset name>
    tplist:
        description: List all stored presets.
        usage: /<command>
    tpinfo:
        description: Get the coordinates of a saved location. 
        usage: /<command> <preset name>
    eject:
        description: Eject from a minecart.
        usage: /<command>
    getchunks:
        description: Reload chunks from the server if some are missing.
        usage: /<command>
    dataval:
        description: Get the data value of a material.
        usage: /<command> <name>
    dataname:
        description: Get the data name of a material.
        usage: /<command> <id>
    gettime:
        description: Get the current game time.
        usage: /<command>
    getcoords:
        description: Get the current coordinates.
        usage: /<command> <player name>
    sendcoords:
        description: Send the current coordinates to another player.
        usage: /<command> <player name>
    kitset:
        description: Create a new item kit preset.
        usage: /<command> <preset name>
    kitget:
        description: Load a kit into your inventory.
        usage: /<command> <preset name>
    kitdel:
        description: Remove a stored item kit.
        usage: /<command> <preset name>
    kitlist:
        description: List stored kit names.
        usage: /<command>
    clearinv:
        description: Empty your inventory.
        usage: /<command>
    lasertag:
        description: Handle creating new laser tag games.
        usage: /<command> <create|players|time|restart|start>
    wrchannelclean:
        description: Clean up issues with wireless redstone channesls.
        usage: /<command>
